---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: localstack
  name: localstack
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: atlassianlabs/localstack:0.6.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4569
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: localstack
spec:
  ports:
    - name: dynamo
      port: 4569
      targetPort: 4569
  selector:
    app: localstack
